version: 2
updates:
  # dependabot for GitHub Actions for this repo
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): github-actions "

  # dependabot for GitHub Actions for the template
  - package-ecosystem: "github-actions"
    directory: "template/.github/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): template github-actions "

  - package-ecosystem: "npm"
    directory: "template/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "chore(deps): template npm packages"
